SET NAMES "utf8";
/* DROP DATABASE IF EXISTS `todolist-app`; */
/* CREATE DATABASE IF NOT EXISTS `todolist-app` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci; */
USE `vVHknCH7Ib`;

CREATE TABLE IF NOT EXISTS todo(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	task CHAR(128) NOT NULL,
	done BOOLEAN DEFAULT false
) ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;
